---
- hosts: mysql
  tasks:
  - include_role:
     name: mysql
     tasks_from: zdp-setup

- hosts: registry
  tasks:
  - include_role:
     name: registry
     tasks_from: install

- hosts: es
  tasks:
  - include_role:
     name: es
     tasks_from: install

- hosts: logstash
  tasks:
  - include_role:
     name: logstash
     tasks_from: install

- hosts: activemq
  tasks:
  - include_role:
     name: activemq
     tasks_from: install

- hosts: lineage
  tasks:
  - include_role:
     name: lineage
     tasks_from: install

- hosts: gateway
  tasks:
  - include_role:
     name: gateway
     tasks_from: install

- hosts: ingestion-warden
  tasks:
  - include_role:
     name: ingestion-warden
     tasks_from: install

- hosts: executor
  tasks:
  - include_role:
     name: executor
     tasks_from: install

- hosts: kibana
  tasks:
  - include_role:
     name: kibana
     tasks_from: install

- hosts: mr
  tasks:
  - include_role:
     name: mr
     tasks_from: install

- hosts: spark
  tasks:
  - include_role:
     name: spark
     tasks_from: install

- hosts: hive
  tasks:
  - include_role:
     name: hive
     tasks_from: install

