---
  - name: Erase existing database when doing fresh installation
    command: mysql -u{{mysql_admin_user}} -p{{mysql_admin_password}}  -e 'DROP DATABASE IF EXISTS {{ zdp_db_name }}'
    when: zdp_upgrade_only  == False

  - name: Create the ZDP Database with name "{{ zdp_db_name }}"
    command: mysql -u{{mysql_admin_user}} -p{{mysql_admin_password}}  -e 'CREATE DATABASE IF NOT EXISTS {{ zdp_db_name }} CHARSET LATIN1'
    when: create_database == True

  - name: Create the ZDP Core User if it doesn't exist and Grant permissions
    command: "mysql -u{{mysql_admin_user}} -p{{mysql_admin_password}} -e \"GRANT ALL ON {{ zdp_db_name }}.* TO \'{{ zdp_db_user}}\'@'%' IDENTIFIED BY \'{{ zdp_db_password }}\'\""
    when: create_database_user == True
